#!/usr/bin/env bash
set -euo pipefail

export PATH="$HOME/.moon/bin:$PATH"

: "${MOONSEO_UPSTREAM_TIMEOUT_SECONDS:=70}"
: "${MOONSEO_DRAFT_MAX_COMPLETION_TOKENS:=1800}"
: "${MOONSEO_DRAFT_RETRY_COUNT:=2}"
: "${MOONSEO_CLAIM_REVIEW_TIMEOUT_SECONDS:=45}"
: "${MOONSEO_CLAIM_REVIEW_MAX_COMPLETION_TOKENS:=1400}"
: "${MOONSEO_CLAIM_REVIEW_RETRY_COUNT:=1}"

export MOONSEO_UPSTREAM_TIMEOUT_SECONDS
export MOONSEO_DRAFT_MAX_COMPLETION_TOKENS
export MOONSEO_DRAFT_RETRY_COUNT
export MOONSEO_CLAIM_REVIEW_TIMEOUT_SECONDS
export MOONSEO_CLAIM_REVIEW_MAX_COMPLETION_TOKENS
export MOONSEO_CLAIM_REVIEW_RETRY_COUNT

moon build cmd/web --target js
./scripts/prepare_web_bundle.sh
python3 ./scripts/dev_server.py
